### ISSUE TITLE
Some non-DEBUG ERP rtm tests fail on hobart

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/rtm#2]
Several ERP tests for rtm fail on hobart, but work as either SMS or ERS tests or on cheyenne.
```
The following tests PASS:
ERP_D_Ld5.f10_f10_musgs.I1850Clm45BgcCru.hobart_nag.rtm-default			
ERP_D_Ld5.f10_f10_musgs.I1850Clm45BgcCru.hobart_nag.rtm-rtmOff			
ERP_D_Ld5.f10_f10_musgs.I1850Clm45BgcCru.hobart_nag.rtm-rtmOnIceOff			
ERP_Ld5.f10_f10_musgs.I1850Clm45BgcCru.hobart_nag.rtm-rtmOff			

While the following tests FAIL:
ERP_D_Ld5.f10_f10_musgs.I1850Clm45BgcCru.hobart_nag.rtm-rtmOnFloodOnEffvelOn		
ERP_Ld5.f10_f10_musgs.I1850Clm45BgcCru.hobart_nag.rtm-default		
ERP_Ld5.f10_f10_musgs.I1850Clm45BgcCru.hobart_nag.rtm-rtmOnFloodOnEffvelOn		
ERP_Ld5.f10_f10_musgs.I1850Clm45BgcCru.hobart_nag.rtm-rtmOnIceOff		
ERP_Ld5.f19_g17.I1850Clm45BgcCru.hobart_nag.rtm-default	
```

The tests that fail all seem to fail after the first simulation is complete, but it doesn't seem to have run the second one, and then complains that the history file for the second one is the same as the first, so it dies on comparison. So I think this might be a problem with the ERP test itself?

```
 ---------------------------------------------------

2018-01-11 17:35:07: Exception during run:
`/scratch/cluster/erik/ERP_Ld5.f19_g17.I1850Clm45BgcCru.hobart_nag.rtm-default.GC.mvystn01_r270nag/run/ERP_Ld5.f19_g17.I1850Clm45BgcCru.hobart_nag.rtm-default.GC.mvystn01_r270nag.rtm.h0.0001-01-04-00000.nc` and `/scratch/cluster/erik/ERP_Ld5.f19_g17.I1850Clm45BgcCru.hobart_nag.rtm-default.GC.mvystn01_r270nag/case2/run/ERP_Ld5.f19_g17.I1850Clm45BgcCru.hobart_nag.rtm-default.GC.mvystn01_r270nag.rtm.h0.0001-01-04-00000.nc` are the same file
Traceback (most recent call last):
  File "/fs/cgd/data0/erik/clm_mvystestlisttoch/cime/scripts/Tools/../../scripts/lib/CIME/SystemTests/system_tests_common.py", line 148, in run
    self.run_phase()
  File "/fs/cgd/data0/erik/clm_mvystestlisttoch/cime/scripts/Tools/../../scripts/lib/CIME/SystemTests/system_tests_compare_two.py", line 217, in run_phase
    self._case_one_custom_postrun_action()
  File "/fs/cgd/data0/erik/clm_mvystestlisttoch/cime/scripts/Tools/../../scripts/lib/CIME/SystemTests/erp.py", line 52, in _case_one_custom_postrun_action
    self.copy_case1_restarts_to_case2()
  File "/fs/cgd/data0/erik/clm_mvystestlisttoch/cime/scripts/Tools/../../scripts/lib/CIME/SystemTests/system_tests_compare_two.py", line 254, in copy_case1_restarts_to_case2
    link_to_restart_files = True)
  File "/fs/cgd/data0/erik/clm_mvystestlisttoch/cime/scripts/Tools/../../scripts/lib/CIME/case_st_archive.py", line 493, in archive_last_restarts
    link_to_last_restart_files=link_to_restart_files)
  File "/fs/cgd/data0/erik/clm_mvystestlisttoch/cime/scripts/Tools/../../scripts/lib/CIME/case_st_archive.py", line 277, in _archive_restarts_date
    link_to_last_restart_files)
  File "/fs/cgd/data0/erik/clm_mvystestlisttoch/cime/scripts/Tools/../../scripts/lib/CIME/case_st_archive.py", line 367, in _archive_restarts_date_comp
    shutil.copy(srcfile, destfile)
  File "/usr/lib64/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/lib64/python2.7/shutil.py", line 69, in copyfile
    raise Error("`%s` and `%s` are the same file" % (src, dst))
Error: `/scratch/cluster/erik/ERP_Ld5.f19_g17.I1850Clm45BgcCru.hobart_nag.rtm-default.GC.mvystn01_r270nag/run/ERP_Ld5.f19_g17.I1850Clm45BgcCru.hobart_nag.rtm-default.GC.mvystn01_r270nag.rtm.h0.0001-01-04-00000.nc` and `/scratch/cluster/erik/ERP_Ld5.f19_g17.I1850Clm45BgcCru.hobart_nag.rtm-default.GC.mvystn01_r270nag/case2/run/ERP_Ld5.f19_g17.I1850Clm45BgcCru.hobart_nag.rtm-default.GC.mvystn01_r270nag.rtm.h0.0001-01-04-00000.nc` are the same file
```

**Comment by ekluzek** [comment]
This is working with updated cime (branch_tags/cime5.8.3_chint17-03) in ctsm1.0.dev049/rtm1_0_68
